# Generated by Django 2.1.5 on 2019-02-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('transit_type', models.CharField(choices=[('public_transit_company', 'Public Transit Company'), ('charter', 'Charter'), ('airporter', 'Airporter'), ('public_ferry', 'Public Ferry'), ('private_ferry', 'Private Ferry'), ('coach_bus', 'Coach Bus'), ('party_bus', 'Party Bus'), ('hop_on_hop_off', 'Hop On Hop Off'), ('rideshare', 'Rideshare'), ('carpool', 'Carpool'), ('scooter', 'Scooter'), ('rental_car', 'Rental Car'), ('bike_share', 'Bike Share')], max_length=200)),
                ('headquarters_location', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=200)),
                ('area_served', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('passenger_train', 'Passenger Train'), ('light_rail', 'Light Rail'), ('bus', 'Bus'), ('ferry', 'Ferry'), ('gondola', 'Gondola'), ('streetcar', 'Streetcar'), ('rideshare', 'Rideshare'), ('bike', 'Bike'), ('scooter', 'Scooter'), ('carpool', 'Carpool'), ('airporter', 'Airporter')], max_length=200)),
                ('start_address', models.CharField(max_length=200)),
                ('end_address', models.CharField(max_length=200)),
                ('amenities', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Company')),
            ],
        ),
    ]
